name: tantivy-jpc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
      - name: Build
        run: cargo build --release && mv target/release/libtantivy_jpc.a go-client/tantivy/packaged/lib/linux-amd64/ && cp -u target/tantivy-jpc.h go-client/tantivy/packaged/include/
      - name: Run tests
        run: cargo test --verbose
      - name: Create Pull Request
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update linux binary
          title: Update libtantivy_jpc.a
          body: Credit new contributors by updating libtantivy_jpc.a
          branch: update-linux-binary
          delete-branch: true
          base: master
          author: JanFalkin <JanFalkin@users.noreply.github.com>
          committer: GitHub <noreply@github.com>
  build-mac:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --release && mv target/release/libtantivy_jpc.a go-client/tantivy/packaged/lib/darwin-amd64/

      - name: Run tests
        run: cargo test --verbose

      - name: Create Pull Request
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update linux binary
          title: Update libtantivy_jpc.a
          body: Credit new contributors by updating libtantivy_jpc.a
          branch: update-darwin-x86_64-binary
          delete-branch: true
          base: master
          author: JanFalkin <JanFalkin@users.noreply.github.com>
          committer: GitHub <noreply@github.com>

  build-mac-arm:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --release --target aarch64-apple-darwin && mv target/aarch64-apple-darwin/release/libtantivy_jpc.a go-client/tantivy/packaged/lib/darwin-aarch64/

      - name: Run tests
        run: cargo test --verbose

      - name: Create Pull Request
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update linux binary
          title: Update libtantivy_jpc.a
          body: Credit new contributors by updating libtantivy_jpc.a
          branch: update-darwin-aarch64-binary
          delete-branch: true
          base: master
          author: JanFalkin <JanFalkin@users.noreply.github.com>
          committer: GitHub <noreply@github.com>
